---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: myjobpod
    spec:
      serviceAccountName: job-sa
      restartPolicy: Never
      securityContext:
        fsGroup: 102
      containers:
        - name: myjobctr
          image: curlimages/curl
          command: ["/bin/sh", "-c"]
          args: ["sleep 3600"]
          securityContext:
            runAsUser: 101
            runAsGroup: 102

