- name: Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap entry from fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Enable IPv4 packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Load module br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Load module overlay
  modprobe:
    name: overlay
    state: present

- name: pre-req containerd packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: setup containerd keyring
  shell: |
    mkdir -p /etc/apt/keyrings
    rm --force /etc/apt/keyrings/docker.gpg
    curl --fail --silent --show-error --location https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --output /etc/apt/keyrings/docker.gpg
    rm --force /etc/apt/sources.list.d/docker.list
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"  | tee /etc/apt/sources.list.d/docker.list

- name: install containerd
  apt:
    name: 
      - containerd.io 
    state: present
    update_cache: yes

- name: configure containerd
  shell: containerd config default | tee /etc/containerd/config.toml

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

