- name: apt kubernetes key
  shell: | 
    rm --force /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    curl --fail --silent --show-error --location https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | gpg --dearmor --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    state: present
    update_cache: yes

- name: copy kubeadm config
  template:
    src: kubeadm-config.yaml.j2
    dest: /home/ubuntu/kubeadm-config.yaml
    mode: 0666
    owner: ubuntu
  vars:
    ip_address: "{{ ansible_default_ipv4.address }}"

- name: install kubernetes components
  apt:
    name:
      - kubelet
      - kubectl
      - kubeadm
      - kubernetes-cni

- name: check for existing
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: initialize control plane
  shell: kubeadm init --config /home/ubuntu/kubeadm-config.yaml    # --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf
  when: kubelet_conf.stat.exists == false

- name: create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: "0755"

- name: Copy admin conf to users directory
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0644"

  # - name: remove node taint
  #  shell: kubectl taint nodes --all node.kubernetes.io/not-ready-

- name: Apply flannel CNI
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml


